name: pokemon_list
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  mobx: ^2.2.1
  flutter_mobx: ^2.1.1
  get_it: ^7.6.4
  dio: ^5.3.3
  cached_network_image: ^3.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.6
  mobx_codegen: ^2.4.0
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true